auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  chunk_encoding: snappy

query_scheduler:
  max_outstanding_requests_per_tenant: 10000

limits_config:
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 30
  cardinality_limit: 500000

chunk_store_config:
  max_look_back_period: 48h

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: "2023-10-12"
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v12
      store: boltdb-shipper

table_manager:
  retention_deletes_enabled: true
  retention_period: 48h

analytics:
  reporting_enabled: false
